export const ROLE_ACCOUNT = {
  ADMIN: 'ADMIN',
  CONTENT_MANAGER: 'CONTENT_MANAGER',
  INSTRUCTOR_MANAGER: 'INSTRUCTOR_MANAGER',
  SUPPORT: 'SUPPORT',
}

export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  REVIEW: 'REVIEW',
  ARCHIVED: 'ARCHIVED',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
}

export const PAGE_SIZE_OPTIONS = [10, 20, 50]
